<?php

namespace My\SurveyBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAllFinishedSurveyUsers($startDate, $endDate)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->select('u, s')
            ->leftJoin('u.survey', 's')
            ->where('u.createdAt < :endDate')
            ->setParameter('endDate', $endDate);
        if ($startDate) {
            $q
                ->andwhere('u.createdAt > :startDate')
                ->setParameter('startDate', $startDate);
        }

        return $q->getQuery()->getResult();
    }
}
