<?php

namespace My\SurveyBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAllFinishedSurveyUsers($startDate)
    {
        $startDate = new \DateTime('-1 day');
        $endDate = new \DateTime('-6 minutes');

        $q = $this
            ->createQueryBuilder('u')
            ->select('u, s')
            ->leftJoin('u.survey', 's')
            ->where('u.createdAt BETWEEN :startDate AND :endDate')
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getQuery();


        return $q->getResult();
    }
}
