country_homepage:
    path:     /
    host:     "{country_alias}.{domain}"
    defaults:
        _controller: MySurveyBundle:Default:country
        domain: "%domain%"
    requirements:
        domain: "%domain%"

my_survey:
    resource: "@MySurveyBundle/Controller/"
    type:     annotation
    prefix:   /